{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "SMS Management",
    "description": "Manage contacts and their messages",
    "contact": {}
  },
  "host": "localhost:3005",
  "basePath": "/api",
  "securityDefinitions": {
    "token": {
      "type": "apiKey",
      "description": "",
      "name": "token",
      "in": "header"
    }
  },
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "description": "Register new user",
        "summary": "Register",
        "tags": [
          "Auth"
        ],
        "operationId": "AuthRegisterPost",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Registerationsuccess"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "contact": {
                  "id": 1,
                  "name": "Name",
                  "email": "email@gmail.com",
                  "phoneNumber": 1234567890
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTY1MTIwNzg1LCJleHAiOjE1NjUyMDcxODV9.aU0N8kg_Z8ukKZvHbj6rrIee2fG73ZdA9HM8AzYrDvs",
                "expiresIn": "24h"
              }
            },
            "headers": {
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Content-Length": {
                "type": "string",
                "default": "287"
              },
              "ETag": {
                "type": "string",
                "default": "W/\"11f-6g6vgQrvL6MxK356wuDcEZKFnNw\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 06 Aug 2019 19:46:25 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              }
            }
          }
        },
        "security": []
      }
    },
    "/auth/login": {
      "post": {
        "description": "Login in user",
        "summary": "Login",
        "tags": [
          "Auth"
        ],
        "operationId": "AuthLoginPost",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Loginsuccess"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "contact": {
                  "id": 1,
                  "name": "Name",
                  "email": "email@gmail.com",
                  "phoneNumber": "1234567890"
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTY1MTIxMzQxLCJleHAiOjE1NjUyMDc3NDF9.C4ew9apIrY45GSNCAuLHfgpPgA5w49TdzllwU5IrgdA",
                "expiresIn": "24h"
              }
            },
            "headers": {
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Content-Length": {
                "type": "string",
                "default": "289"
              },
              "ETag": {
                "type": "string",
                "default": "W/\"121-/7jrTnz/r7ciePhMiIKL+5cKBn8\""
              },
              "Date": {
                "type": "string",
                "default": "Tue, 06 Aug 2019 19:55:41 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              }
            }
          }
        },
        "security": []
      }
    },
    "/sms": {
      "post": {
        "description": "Send sms/message to a specified phone number",
        "summary": "Send message",
        "tags": [
          "SMS"
        ],
        "operationId": "SmsPost",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SendmessageRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/SendSMSsuccess"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "message": "Hello my new friend",
                "from": "1234567890",
                "to": "2234567890"
              }
            },
            "headers": {
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Content-Length": {
                "type": "string",
                "default": "71"
              },
              "ETag": {
                "type": "string",
                "default": "W/\"47-vFX5Yb1Tnwvx9sUUfuCaTXecMkc\""
              },
              "Date": {
                "type": "string",
                "default": "Sat, 10 Aug 2019 16:14:51 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              }
            }
          }
        }
      },
      "get": {
        "description": "Get the messages of a logged in user",
        "summary": "Get messages",
        "tags": [
          "SMS"
        ],
        "operationId": "SmsGet",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Getmessagessuccess"
              }
            },
            "examples": {
              "application/json; charset=utf-8": [
                {
                  "id": 3,
                  "message": "Can we be friends",
                  "status": "read",
                  "toId": 5,
                  "fromId": 4,
                  "createdAt": "2019-08-10T16:13:27.716Z",
                  "updatedAt": "2019-08-10T16:32:04.91Z"
                },
                {
                  "id": 5,
                  "message": "Hello my new friend",
                  "status": "read",
                  "toId": 5,
                  "fromId": 4,
                  "createdAt": "2019-08-10T16:14:51.501Z",
                  "updatedAt": "2019-08-10T16:32:04.91Z"
                },
                {
                  "id": 4,
                  "message": "Sure we can",
                  "status": "read",
                  "toId": 4,
                  "fromId": 5,
                  "createdAt": "2019-08-10T16:13:51.963Z",
                  "updatedAt": "2019-08-10T16:33:59.253Z"
                }
              ]
            },
            "headers": {
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Content-Length": {
                "type": "string",
                "default": "456"
              },
              "ETag": {
                "type": "string",
                "default": "W/\"1c8-Czz7xKm7DMUGVgKj5TMiK19Wujg\""
              },
              "Date": {
                "type": "string",
                "default": "Sat, 10 Aug 2019 16:35:35 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              }
            }
          }
        }
      }
    },
    "/contact": {
      "delete": {
        "description": "Delete contact",
        "summary": "Delete contact",
        "tags": [
          "Contacts"
        ],
        "operationId": "ContactDelete",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "description": "Update contact's name, email or phone number",
        "summary": "Update contact",
        "tags": [
          "Contacts"
        ],
        "operationId": "ContactPut",
        "deprecated": false,
        "produces": [
          "application/json; charset=utf-8"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdatecontactRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Updatecontactsuccess"
            },
            "examples": {
              "application/json; charset=utf-8": {
                "contact": {
                  "id": 4,
                  "name": "Megame Awesome",
                  "email": "megame@gmail.com",
                  "phoneNumber": "1234567890",
                  "createdAt": "2019-08-10T16:12:49.751Z",
                  "updatedAt": "2019-08-10T17:39:44.598Z"
                }
              }
            },
            "headers": {
              "X-Powered-By": {
                "type": "string",
                "default": "Express"
              },
              "Content-Length": {
                "type": "string",
                "default": "176"
              },
              "ETag": {
                "type": "string",
                "default": "W/\"b0-ynz3rKzRsJbFkeUyGah8bu/AJJc\""
              },
              "Date": {
                "type": "string",
                "default": "Sat, 10 Aug 2019 17:39:44 GMT"
              },
              "Connection": {
                "type": "string",
                "default": "keep-alive"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "RegisterRequest": {
      "title": "RegisterRequest",
      "example": {
        "name": "Name",
        "password": "P@ssw0rd",
        "phoneNumber": "1234567890",
        "email": "email@gmail.com"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "password",
        "phoneNumber",
        "email"
      ]
    },
    "Registerationsuccess": {
      "title": "Registerationsuccess",
      "example": {
        "contact": {
          "id": 1,
          "name": "Name",
          "email": "email@gmail.com",
          "phoneNumber": 1234567890
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTY1MTIwNzg1LCJleHAiOjE1NjUyMDcxODV9.aU0N8kg_Z8ukKZvHbj6rrIee2fG73ZdA9HM8AzYrDvs",
        "expiresIn": "24h"
      },
      "type": "object",
      "properties": {
        "contact": {
          "$ref": "#/definitions/Contact"
        },
        "token": {
          "type": "string"
        },
        "expiresIn": {
          "type": "string"
        }
      },
      "required": [
        "contact",
        "token",
        "expiresIn"
      ]
    },
    "Contact": {
      "title": "Contact",
      "example": {
        "id": 1,
        "name": "Name",
        "email": "email@gmail.com",
        "phoneNumber": 1234567890
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "id",
        "name",
        "email",
        "phoneNumber"
      ]
    },
    "LoginRequest": {
      "title": "LoginRequest",
      "example": {
        "email": "email@gmail.com",
        "password": "P@ssw0rd"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "Loginsuccess": {
      "title": "Loginsuccess",
      "example": {
        "contact": {
          "id": 1,
          "name": "Name",
          "email": "email@gmail.com",
          "phoneNumber": "1234567890"
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTY1MTIxMzQxLCJleHAiOjE1NjUyMDc3NDF9.C4ew9apIrY45GSNCAuLHfgpPgA5w49TdzllwU5IrgdA",
        "expiresIn": "24h"
      },
      "type": "object",
      "properties": {
        "contact": {
          "$ref": "#/definitions/Contact1"
        },
        "token": {
          "type": "string"
        },
        "expiresIn": {
          "type": "string"
        }
      },
      "required": [
        "contact",
        "token",
        "expiresIn"
      ]
    },
    "Contact1": {
      "title": "Contact1",
      "example": {
        "id": 1,
        "name": "Name",
        "email": "email@gmail.com",
        "phoneNumber": "1234567890"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "email",
        "phoneNumber"
      ]
    },
    "SendmessageRequest": {
      "title": "SendmessageRequest",
      "example": {
        "message": "Hello my new friend",
        "recipientNumber": "2234567890"
      },
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "recipientNumber": {
          "type": "string"
        }
      },
      "required": [
        "message",
        "recipientNumber"
      ]
    },
    "SendSMSsuccess": {
      "title": "SendSMSsuccess",
      "example": {
        "message": "Hello my new friend",
        "from": "1234567890",
        "to": "2234567890"
      },
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        }
      },
      "required": [
        "message",
        "from",
        "to"
      ]
    },
    "Getmessagessuccess": {
      "title": "Getmessagessuccess",
      "example": {
        "id": 3,
        "message": "Can we be friends",
        "status": "read",
        "toId": 5,
        "fromId": 4,
        "createdAt": "2019-08-10T16:13:27.716Z",
        "updatedAt": "2019-08-10T16:32:04.91Z"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "toId": {
          "type": "integer",
          "format": "int32"
        },
        "fromId": {
          "type": "integer",
          "format": "int32"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "message",
        "status",
        "toId",
        "fromId",
        "createdAt",
        "updatedAt"
      ]
    },
    "UpdatecontactRequest": {
      "title": "UpdatecontactRequest",
      "example": {
        "name": "Megame Awesome"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "Updatecontactsuccess": {
      "title": "Updatecontactsuccess",
      "example": {
        "contact": {
          "id": 4,
          "name": "Megame Awesome",
          "email": "megame@gmail.com",
          "phoneNumber": "1234567890",
          "createdAt": "2019-08-10T16:12:49.751Z",
          "updatedAt": "2019-08-10T17:39:44.598Z"
        }
      },
      "type": "object",
      "properties": {
        "contact": {
          "$ref": "#/definitions/Contact2"
        }
      },
      "required": [
        "contact"
      ]
    },
    "Contact2": {
      "title": "Contact2",
      "example": {
        "id": 4,
        "name": "Megame Awesome",
        "email": "megame@gmail.com",
        "phoneNumber": "1234567890",
        "createdAt": "2019-08-10T16:12:49.751Z",
        "updatedAt": "2019-08-10T17:39:44.598Z"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phoneNumber": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "email",
        "phoneNumber",
        "createdAt",
        "updatedAt"
      ]
    }
  },
  "security": [
    {
      "token": []
    }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": ""
    },
    {
      "name": "SMS",
      "description": ""
    },
    {
      "name": "Contacts",
      "description": ""
    }
  ]
}